### ISSUE TITLE
Can't execute bill-setup task

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#161]
From @LyndonZhao:

Description:
Can't execute bill-setup task in the guide document.

dataflow version:
export DATAFLOW_VERSION=2.2.0.RELEASE
export SKIPPER_VERSION=2.1.2.RELEASE

cat stdout.log
```
. ____ _ __ _ _
/\ / ' __ _ () __ __ _ \ \ \
( ( )__ | '_ | '| | ' / ` | \ \ \
\/ )| |)| | | | | || (| | ) ) ) )
' || .__|| ||| |_, | / / / /
=========||==============|/=////
:: Spring Boot :: (v2.1.6.RELEASE)

2019-11-27 16:01:59.699 INFO 119 --- [ main] i.s.b.BillsetuptaskApplication : Starting BillsetuptaskApplication v0.0.1-SNAPSHOT on 4ffbcccc6e3a with PID 119 (/usr/local/spring-cloud-dataflow/register-app/billsetuptask-0.0.1-SNAPSHOT.jar started by root in /tmp/bill-setup-task1316090555936135858/1215216204882/bill-setup-task-79c84cad-6a13-4f39-9b2d-f33090ec9940)
2019-11-27 16:01:59.705 INFO 119 --- [ main] i.s.b.BillsetuptaskApplication : No active profile set, falling back to default profiles: default
2019-11-27 16:02:01.710 INFO 119 --- [ main] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
2019-11-27 16:02:02.608 INFO 119 --- [ main] com.alibaba.druid.pool.DruidDataSource : {dataSource-1} inited
2019-11-27 16:02:02.745 DEBUG 119 --- [ main] o.s.c.t.c.SimpleTaskAutoConfiguration : Using org.springframework.cloud.task.configuration.DefaultTaskConfigurer TaskConfigurer
2019-11-27 16:02:02.747 DEBUG 119 --- [ main] o.s.c.t.c.DefaultTaskConfigurer : No EntityManager was found, using DataSourceTransactionManager
2019-11-27 16:02:03.476 DEBUG 119 --- [ main] o.s.c.t.r.s.TaskRepositoryInitializer : Initializing task schema for mysql database
2019-11-27 16:02:04.305 ERROR 119 --- [ main] o.s.c.t.listener.TaskLifecycleListener : An event to end a task has been received for a task that has not yet started.
2019-11-27 16:02:04.306 WARN 119 --- [ main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 10 task is already complete
2019-11-27 16:02:04.376 INFO 119 --- [ main] com.alibaba.druid.pool.DruidDataSource : {dataSource-1} closed
2019-11-27 16:02:04.395 ERROR 119 --- [ main] o.s.c.t.listener.TaskLifecycleListener : An event to end a task has been received for a task that has not yet started.
2019-11-27 16:02:04.408 INFO 119 --- [ main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-11-27 16:02:04.429 ERROR 119 --- [ main] o.s.boot.SpringApplication : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 10 task is already complete
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
at io.spring.billsetuptask.BillsetuptaskApplication.main(BillsetuptaskApplication.java:10) [classes!/:0.0.1-SNAPSHOT]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 10 task is already complete
at org.springframework.util.Assert.isNull(Assert.java:159) ~[spring-core-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:261) ~[spring-cloud-task-core-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:390) ~[spring-cloud-task-core-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
... 20 common frames omitted
```

**Comment by LyndonZhao** [comment]
Hi, Mr. sabbyanandan,

Is there any advice for this problem?
Thanks very much.

**Comment by LyndonZhao** [comment]
@cppwfs 

Hi, Mr. cppwfs ,

Is there any advice for this problem?
Thanks very much.

**Comment by cppwfs** [comment]
Hello @LyndonZhao ,
Thanks for the issue!
So let's take a look at this:

**What does the error mean**
Basically it means that the when you executed this task it had the `spring.cloud.task.execution-id` set to 10.   However there was already a task execution in the database with the execution-id of 10 that had already executed and completed.   

**How did this execution-id get set**
When a user requests a task launch from Spring Cloud Data Flow, it creates a entry in the `task-execution` table  and then launches the task with the `spring.cloud.task.execution-id` set to the next available `task-execution-id`.   When your task runs it will populate this task-execution record as it precedes with the execution.

**How did this error occur**
This is where you can help me.   Can you provide the steps that you took prior to getting this error?  Also provide the database and platform you were deploying to (local, Cloud Foundry, Kubernetes).  

** Work Around **
Re-launch the task, either from the command line or from Spring Cloud Data Flow and it will increment to the next available task execution id.

**Comment by LyndonZhao** [comment]
Hello, Mr. cppwfs
I use MySql and deploying to local.
And this problem it is an always issue. when I click the "launch the task" button in 
http://localhost:9393/dashboard/#/tasks/definitions/launch/bill-setup-task, it will always error.

The belowing is my configuration file application.yml.  help it can help to to check this issue.


`
spring:
  application:
    name: Bill Setup Task
  datasource:
    name: springCloudDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/springclouddataflow?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: xxxxx
      password: xxxx
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #默认值本来就是false, 这里是强调
      default-auto-commit: false
logging:
  level:
    org.springframework.cloud.task: debug
`

**Comment by LyndonZhao** [comment]
By the way, the below error was met too when I launch the taskl.

org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 6 not found
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at io.spring.billsetuptask.BillsetuptaskApplication.main(BillsetuptaskApplication.java:10) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [billsetuptask-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 6 not found
	at org.springframework.util.Assert.notNull(Assert.java:198) ~[spring-core-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:260) ~[spring-cloud-task-core-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:390) ~[spring-cloud-task-core-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]

**Comment by LyndonZhao** [comment]
And here is the records in my DB.

MySQL [dataflow]> select * from TASK_EXECUTION;
+-------------------+------------+----------+-----------------+-----------+--------------+---------------+---------------------+------------------------------------------------------+---------------------+
| TASK_EXECUTION_ID | START_TIME | END_TIME | TASK_NAME       | EXIT_CODE | EXIT_MESSAGE | ERROR_MESSAGE | LAST_UPDATED        | EXTERNAL_EXECUTION_ID                                | PARENT_EXECUTION_ID |
+-------------------+------------+----------+-----------------+-----------+--------------+---------------+---------------------+------------------------------------------------------+---------------------+
|                 2 | NULL       | NULL     | mytask1         |      NULL | NULL         | NULL          | 2019-11-27 11:58:23 | mytask1-574e6ac4-35e4-4925-a0d3-0dcce2f3ce37         |                NULL |
|                 3 | NULL       | NULL     | mytask1         |      NULL | NULL         | NULL          | 2019-11-27 12:28:34 | mytask1-a0f78f14-b4c9-4ec1-ae5c-47c5de3d5b3a         |                NULL |
|                 4 | NULL       | NULL     | bill-setup-task |      NULL | NULL         | NULL          | 2019-11-27 12:30:54 | bill-setup-task-ba2d1833-cf7d-40f9-ad9d-b52fb1ab0c2a |                NULL |
|                 5 | NULL       | NULL     | bill-setup-task |      NULL | NULL         | NULL          | 2019-12-06 07:03:48 | bill-setup-task-89108fdc-e793-4612-95ee-e5221d060a7f |                NULL |
|                 6 | NULL       | NULL     | bill-setup-task |      NULL | NULL         | NULL          | 2019-12-06 07:29:10 | bill-setup-task-13ca95c9-93bd-43aa-bf08-1bd03bd797fa |                NULL |
+-------------------+------------+----------+-----------------+-----------+--------------+---------------+---------------------+------------------------------------------------------+---------------------+
5 rows in set (0.00 sec)

**Comment by cppwfs** [comment]
From the information you have provided it looks like the SCDF instance is using a different database than your task.
i.e. your dataflow is using database A and your task is using database B.   
We can see this in your `select` from above where dataflow is putting its stub task execution entries into the database.   However your task can not see the task execution entry as shown with the `IllegalArgumentException` from the entry above.  

**Suggestions**
You shouldn't need to declare your datasource information in your application.yml.   This is provided by SCDF at launch time, so remove those from the application.yml.

**Possible Cause**
This can be caused if your SCDF or your task don't have the same database dependencies.   Verify the database dependencies for Spring Cloud Data Flow and your task app are the same. 

If the instructions in the **Suggestions** and **Possible Cause** don't solve the issue, please providing us full logs, this may give us the information for us to isolate the issue.

**Comment by LyndonZhao** [comment]
Hello, Mr. cppwfs
Yes, you are right, I use the different datasource for task with SCDF.
Actually, that is exactly what we need. 
So I wonder if it is possible to have different datasource for my task with SCDF?

Thanks very much^^.

**Comment by cppwfs** [comment]
Hello @LyndonZhao ,
Absolutely!    Take a look at this example:
https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/multiple-datasources
This example shows you how to implement a Spring Cloud Task app with multiple datasources (1 for task and the other(s) for your application needs).

**Comment by LyndonZhao** [comment]
OK, Thanks very much.

**Comment by cppwfs** [comment]
Awesome!  Then,  I'll close this issue.

**Comment by LyndonZhao** [comment]
Hello, Mr. cppwfs


I tried to add a H2 datasource, but it still the same error.
I have uploaded my codes, would you please help to check it?
[billsetuptask.zip](https://github.com/spring-io/dataflow.spring.io/files/3961672/billsetuptask.zip)

Thanks very much.

**Comment by cppwfs** [comment]
Can you share this project via github.   I'm not really allowed to open zips.

**Comment by sabbyanandan** [comment]
Closing this is due to no activity.
